### ISSUE TITLE
Base all proofs in theory `Communication` on the `equivalence` proof method

### ISSUE THREAD

**Issue by javierdiaz72** [input-output-hk/fm-ouroboros#134]
Currently the proofs of lemmas in theory `Communication` are based on traditional proof methods such as `blast`. However, the proper way to prove such lemmas is to use the `equivalence` proof method.

Our goal is to modify the proofs of those lemmas such that they use the `equivalence` method in order to obtain nicer proofs.

**Comment by jeltsch** [comment]
This issue has been superseded by #144.
