### ISSUE TITLE
is there a way to generate a pdf or some kind of easily read documentation file on this?

### ISSUE THREAD

**Issue by greggdourgarian** [input-output-hk/fm-ouroboros#2]
tx in advance...i understood from a tweet by Charles that there was a pdf here for Chi Calculus (link: https://twitter.com/IOHK_Charles/status/999453156319752192)

**Comment by jeltsch** [comment]
To turn the documented χ-calculus formalization into a PDF file, you have to [install Isabelle][isabelle-installation], clone this repository, switch to the `chi-calculus-formalization` branch, go to the `Chi_Calculus` subdirectory, and run `make`. The PDF will end up in `Chi_Calculus/output/document.pdf`. If you want, I can also send you a PDF by e-mail.

In any case, please note that this is still work in progress. Most of the job is done, but some proofs and parts of the documentation are still missing.

[isabelle-installation]:
    https://isabelle.in.tum.de/installation.html
    "Isabelle Installation"

**Comment by jeltsch** [comment]
Some things have changed meanwhile. Now the current state of the χ-calculus formalization is in `master` in the `Isabelle` subdirectory, and updated building instructions are provided in the `README.md` file in this directory.
